[project]
name = "Study-ToxicComment"
version = "0.1.0"
authors = [{ name = "Дмитрий Бервинов" }]
license = { text = "MIT" }
requires-python = ">= 3.11.9"
dependencies = [
    "jupyterlab>=4.4.7",
    "notebook>=7.4.5",
]
